# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3880a4c5397c032d6c052b6da76380bffa47c73e15a678a2fd9eeb3b6dabe47d46c5c0a3c2c67f5e3b4b11a4d81a92f8a3d2d6ab054ed1995f259f77c0713e9

test:
  secret_key_base: 734db22a1d54a489bcc6843f190cc1ca2d28df3ac5afd1da3f1d10e3b2ba404626141a42c4009da262b68aa1de9b51a6023603c7b49f4dff1c41d61a2d05a5f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
